# Generated by Django 2.1.1 on 2018-11-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='db_choice',
        ),
    ]
